### ISSUE TITLE
questions on eval.py and test.py

### ISSUE THREAD

**Issue by Dr-Zhuang** [ezeli/Transformer_model#1]
It seems the eval.py and test.py come from yours BUTD_model, which don't use Transformer model. 

chkpoint = torch.load(opt.eval_model, map_location=lambda s, l: s)
decoder = Decoder(chkpoint['idx2word'], chkpoint['settings'])
decoder.load_state_dict(chkpoint['model'])

When I use the trained models, there will be errors in eval.py.

**Comment by ezeli** [comment]
Thanks for correcting, I have modified it.
