### ISSUE TITLE
评价指标

### ISSUE THREAD

**Issue by Originhhh** [ezeli/Transformer_model#2]
您好，我现在结束训练后，想获得那些测试评价指标的分数，就像您readme中显示的那样，请问要想获得那些分数，要如何做呢

**Comment by ezeli** [comment]
请参考：ezeli/BUTD_model#6

**Comment by ezeli** [comment]
请参考：https://github.com/ezeli/BUTD_model/issues/6#issuecomment-835147710

**Comment by Originhhh** [comment]
好的谢谢
